name: scheduled_run

on:
  schedule:
    - cron: "* */3 * * *"   # Every 3 hours

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Run
        run: |
          curl -sSf https://wutsi-twitter-prod.herokuapp.com/actuator/health >> /dev/null


